### ISSUE TITLE
User Auth Complete + Heroku Hosting

### ISSUE THREAD

**Issue by ase1210** [ase1210/Cluck#2]
Hey Andy,  

I've completed the following:

1. Hosting on Heroku (02/26/27) -
https://cluck-cluck.herokuapp.com/#/

2. New account creation, login, and guest/demo login (02/28/19 - 2.5 days)

- Users can sign up, sign in, log out
- Users can use a demo login to try the site
- Users can't use certain features without logging in (sending or viewing messages)

I'm not a huge fan of my login/signup form yet, but plan to revisit the CSS when i do the CSS for  my channels MVP..... I used grid for the splash page which i did last, so will likely make the signup/login form grid as well.  

Let me know what you think.... and anything i overlooked..... break the site!

**Comment by andywynkoop** [comment]
I'm doing my best to break it! Here are a few things I think you should change so far:
 - [x] Even though you're not doing workspaces as an MVP, your forms should still match the styling of the original site exactly - including things like border-radius, inputs, colors, etc. Make it look perfect before moving on.
- [x] Font for login/ signup header is too large
- [x] Add the grey background around the form
- [x] Navbar buttons are too small
- [x] Get started button might need more padding
- [x] Add appropriate border-radius to buttons, input fields, form, etc.
- [x] All navbar links, even the ones that don't do anything should appear clickable - style with `curson: pointer`
- [x] Either: match the styling of the slack errors or increase the size of the form so that the form doesn't stretch when you render errors. 
- [x] When logged in or logged out, if I visit a nonsense route, `/bologna`, I should be redirected to `/` or see some sort of 404 page
- [ ] The logged in navbar should be styled like the actual site - I think you should at least make the sidebar component and its dropdown for the logout button.
- [x] username shouldn't be case sensitive and you should prevent users from signing up with the same username with different casing (this should be about a 5-10 minute change, let me know if you get stuck trying to do this)

Overall, this looks pretty good, you just need to work on your styling - you should aim for an exact clone of slack, and try to match their style when making any different components. CSS will be a lot less overwhelming if you do it completely at each step

**Comment by ase1210** [comment]
i thought Eli told us not to have cursor pointer on links that go nowhere.....

**Comment by ase1210** [comment]
I've completed all the items here except the logged in navbar styling.  I will do that when i style the channels components since they will be designed together in the same column.    

Let me know if any of your other suggested changes need additional improvement.
